### ISSUE TITLE
TransactionalEventPublisher not publish events after exception

### ISSUE THREAD

**Issue by melodi-c** [prooph/humus-amqp-producer#20]
Hello.
I have an event consumer that executes commands based on events (saga pattern). If I get a ConcurrencyException while the aggregate is being saved, the event publisher stops sending messages.

I think the problem is that after the ConcurrencyException the $inTransaction TransactionalEventPublisher field does not switch to false and the rest of the events just get in the queue

**Comment by prolic** [comment]
can you provide a test case?

**Comment by prolic** [comment]
probably here https://github.com/prooph/humus-amqp-producer/blob/master/src/TransactionalEventPublisher.php#L85 we need to add the change. But having a test-case at hand would be really good, so we can cover this scenario in the unit tests.

**Comment by melodi-c** [comment]
@prolic, I wrote a test ( not a professional in this :) )
```php
 /**
     * @test
     */
    public function it_publish_after_rollback(): void
    {
        $eventStore = $this->prophesize(TransactionalEventStore::class);
        $eventStore = new TransactionalActionEventEmitterEventStore($eventStore->reveal(), new ProophActionEventEmitter());

        $streamName = new StreamName('test-stream');

        $event1 = new TestDomainEvent(['foo' => 'baz']);
        $event2 = new TestDomainEvent(['foo' => 'bar']);

        $eventBus = $this->prophesize(EventBus::class);
        $eventBus->dispatch($event1)->willThrow(\Exception::class);
        $eventBus->dispatch($event2)->shouldBeCalled();

        $producer = $this->prophesize(Producer::class);

        $plugin = new TransactionalEventPublisher($eventBus->reveal(), $producer->reveal());
        $plugin->attachToEventStore($eventStore);

        $eventStore->beginTransaction();

        $eventStore->create(
            new Stream($streamName, new ArrayIterator())
        );

        $eventStore->appendTo($streamName, new ArrayIterator([$event1]));

        try {
            $eventStore->commit();
        } catch (\Throwable $exception) {
            $eventStore->rollback();
        }

        $eventStore->appendTo($streamName, new ArrayIterator([$event2]));

        $eventStore->commit();
    }
```

if I add this line 
```php
$this->inTransaction = false; 
``` 
to https://github.com/prooph/humus-amqp-producer/blob/master/src/TransactionalEventPublisher.php#L85 the test passes

**Comment by prolic** [comment]
@melodi-c great work! Can you provide a pull request?
